### ISSUE TITLE
Add support for attaching and detaching volumes

### ISSUE THREAD

**Issue by bburtin** [brkt/fog-brkt-ruby#15]
For NUC-8783, we're adding a new endpoint for attaching and detaching volumes. We'll need to update the Ruby Fog SDK to support the new endpoint.

**Comment by tzvetkoff** [comment]
What should we do with current attach/detach implementations? (they change the `instance` id on the volume)
I'd assume we're about to change this in favour VolumeAttachment.

**Comment by girishbrkt** [comment]
We have disabled updating the instance id associated with a Brkt Volume via the API. Attach/detach operations should use the brktvolumeattachment APIs
