### ISSUE TITLE
Support instance pause and resume

### ISSUE THREAD

**Issue by bburtin** [brkt/fog-brkt-ruby#16]
Once NUC-9037 is fixed, we'll need to make sure that the Ruby Fog SDK supports pausing and resuming an individual instance.

**Comment by uzzz** [comment]
How pause and resume operations are performed using API? Didn't find it in a documentation. Change requested_state attribute and send an update request?

**Comment by bburtin** [comment]
Check with Gary.  There may be nothing to do here if it's just a matter of POSTing a new value for requested_state.
